name: Linux ARM (Docker)

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.2.0

      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: docker/setup-qemu-action@v1
          
      - name: Build with Docker
        run: |
          docker build \
            -t xxx-linux-arm:latest \
            --output=type=docker \
            --platform=linux/arm64 \
            ./docker
      - name: Extract build files from Docker instance
        run: |
          docker create -ti --name xxx-linux-arm-tmp xxx-linux-arm bash
          docker cp xxx-linux-arm-tmp:/home/rust/src/autoadb .

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: autoadb
      #     path: autoadb
          